(Task 51) Apply Swagger best practices
abbcyhn/homeder-backend pull request #15
Opened 2023-10-21 15:57 UTC by smrsgv

2023-10-22 10:10 UTC, abbcyhn requested changes

2023-10-22 10:10 UTC, abbcyhn commented on Application/Users/Features/UpdateUser/UpdateUserInput.cs
> +    public UserType UserType { get; set; }
Birthdate property date format should be seem in swagger as "dd-MM-yyyy"

2023-10-22 16:22 UTC, abbcyhn requested changes

2023-10-22 16:22 UTC, abbcyhn commented on WebAPI/Extensions/SwaggerServiceExtensions.cs
> +﻿using Microsoft.AspNetCore.Authentication.JwtBearer;
Good

2023-10-22 20:11 UTC, smrsgv commented on Application/Users/Features/UpdateUser/UpdateUserInput.cs
> +    public UserType UserType { get; set; }
According to best practices described in [The 5 laws of API dates and times](https://apiux.com/2013/03/20/5-laws-api-dates-and-times/) article I decided to set format as "yyyy-MM-dd"

2023-10-23 05:56 UTC, abbcyhn approved these changes

2023-10-23 05:57 UTC, merged